report.time.unit=MILLIS
report.time.aggregation=min
test.benchmark.runs=5

report.suites=sorting
report.sorting.dir=tests/hw06/2.sorted
report.sorting.tasks=selection_sort,heap_sort
report.sorting.rowkey=single_number