#test.dir=tests/hw06/2.sorted
test.input.ext=.in
test.output.ext=.out
test.compare=trim
test.show.passed=true
test.show.failed=true
test.show.diff=true
test.time.enabled=true
test.time.unit=millis
test.benchmark.runs=5
test.timeout.enabled=true
test.timeout.millis=5000
test.task.type=sorting
test.task.id=selection_sort
