test.dir=tests/hw21/fraction
test.input.ext=.in
test.output.ext=.out
test.compare=trim
test.show.passed=true
test.show.failed=true
test.show.diff=true
test.time.enabled=true
test.time.unit=millis
test.benchmark.runs=1
test.timeout.enabled=true
test.timeout.millis=10000
test.task.type=dynamic_programming
test.task.id=fraction-sum