report.time.unit=MILLIS
report.time.aggregation=min
test.benchmark.runs=5

report.suites=sorting
report.sorting.dir=tests/hw06/0.random
report.sorting.tasks=bubble_sort,bubble_sort_optimized,insertion_sort_shift,insertion_sort_binary,shell_sort,shell_sort_knuth,shell_sort_ciura
report.sorting.rowkey=single_number